{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "UepYZWDX5lTPQjv/Fb1KYUOT9kchl5UeMMICGcH6IZiIcZeODsLcksBNspy3TZWD46A9GUYql0Az9oOBDA1jVMZ95qLJKRWmX3/MCEjYiSAlg7EwEBNXcamcR9W\u002B2H8ggba/cZfyoywDxJhlQSM62U7WilDJJCouo2W4drVQVbYfJ53iVoCzsx68P5cxZ\u002Bvg7O83SzkJkoUoC\u002BoHRJyMWrs3cyRqRKb82alrleVR2K0Ea\u002BG5cq1ISuNWM3438SQAE14pbrA5Nwh\u002B\u002BJ8mNqv2iM\u002Bwz8qdpWOnX1JtUac2/MgzCadYGtWXF3Sy5C6uZSI/epXzNGIamYEWxpqXdHkoEUToUsC\u002Bukcs/CqRQAj17I\u002BccocLZm\u002BzJxAc4rLd7XtZdChxKCa21TiQTgSF3uDjD3fES1sEYlda3Ba4D1StSoq2hpae9MdTwNTC0YaBU8UwpIjhwZqoLytT2qceeHlaQ6H1tLSeXy6XXgGj1DPuqiy0ZDzs\u002Bxhh1qloshadxYxrI4xNgr2W/tOwgsKz3b\u002BKBYU65CMYe4KNLpwMJuyMo6XoSYdHm4aYOZ\u002BA\u002BZjj3NGd6EvJDYwzq09hXFpuRrT7BPnhZkGmVbdUMVfXqGKbA2q1JrG\u002BkgMIRom6AdVdgKM6TVb7fY3ksRTl2qj2c2yyCZBrM6C98dMN8zF1k6n2tvw="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "perl" : [
      "5.26",
      "5.14"
   ],
   "script" : "make test"
}
